export const API = {
  AUTH: {
    LOGIN: '/auth/login/',
    FIREBASE_LOGIN: '/auth/firebase-login/',
    REFRESH: '/auth/refresh/',
    LOGOUT: '/auth/logout/',
    ACTIVATE: '/auth/activate/',
    ME: '/auth/me/',
    CHANGE_PASSWORD: '/auth/change-password/',
    PASSWORD_RESET: '/auth/password-reset/',
    PASSWORD_RESET_CONFIRM: '/auth/password-reset/confirm/',
  },
  USERS: {
    BASE: '/users/',
    ME: '/users/me/',
    UPLOAD_AVATAR: '/users/upload_avatar/',
    STATS: '/users/stats/',
    EXECUTIVES: '/users/executives/',
    FOUNDERS: '/users/founders/',
    FOUNDER_DETAIL: (id: string) => `/users/founders/${id}/`,
    ADD_FOUNDER_SHARES: (id: string) => `/users/founders/${id}/add_shares/`,
    RENEW_FOUNDER_SHARES: (id: string) => `/users/founders/${id}/renew_shares/`,
    REMOVE_SHARE_ADJUSTMENT: (founderId: string, adjustmentId: string) =>
      `/users/founders/${founderId}/remove_share_adjustment/?adjustment_id=${adjustmentId}`,
    BY_SCHOOL: (schoolId: string) => `/users/by_school/?school_id=${schoolId}`,
    DETAIL: (id: string) => `/users/${id}/`,
    TOGGLE_LICENSE: (id: string) => `/users/${id}/toggle_license/`,
    UPDATE_ROLE: (id: string) => `/users/${id}/update_role/`,
  },
  SCHOOLS: {
    BASE: '/schools/schools/',
    MY_SCHOOL: '/schools/schools/my_school/',
    STATS: '/schools/schools/stats/',
    DETAIL: (id: string) => `/schools/schools/${id}/`,
    TOGGLE_STATUS: (id: string) => `/schools/schools/${id}/toggle_status/`,
    SETTINGS: (id: string) => `/schools/settings/${id}/`,
    HIERARCHY_STAFF: '/schools/hierarchy/staff/',
    HIERARCHY_SUB_SCHOOLS: '/schools/hierarchy/sub-schools/',
    HIERARCHY_SUB_SCHOOL_DETAIL: (id: string) => `/schools/hierarchy/sub-schools/${id}/`,
    HIERARCHY_SUB_ADMINS: '/schools/hierarchy/sub-admins/',
    HIERARCHY_SUB_ADMIN_DETAIL: (id: string) => `/schools/hierarchy/sub-admins/${id}/`,
    HIERARCHY_CLASSES: '/schools/hierarchy/classes/',
    HIERARCHY_CLASS_DETAIL: (id: string) => `/schools/hierarchy/classes/${id}/`,
    HIERARCHY_CLASS_EXPLORE: (id: string) => `/schools/hierarchy/classes/${id}/explore/`,
    HIERARCHY_SUBJECTS: '/schools/hierarchy/subjects/',
    HIERARCHY_SUBJECT_DETAIL: (id: string) => `/schools/hierarchy/subjects/${id}/`,
  },
  PLATFORM: {
    SETTINGS: '/platform/settings/',
    UPLOAD_LOGO: '/platform/upload-logo/',
    UPLOAD_EVENT_MEDIA: '/platform/upload-event-media/',
    FEES: '/platform/fees/',
    EVENTS: '/platform/events/',
    TUTORIALS: '/platform/tutorials/',
    STATS: '/platform/stats/',
    EVENT_DETAIL: (id: string) => `/platform/events/${id}/`,
  },
  LIVE_CLASSES: {
    BASE: '/live-classes/',
    DETAIL: (id: string) => `/live-classes/${id}/`,
    MY_CLASSES: '/live-classes/my_classes/',
    ENROLLED: '/live-classes/enrolled/',
    LIVE_NOW: '/live-classes/live_now/',
    UPCOMING: '/live-classes/upcoming/',
    STATS: '/live-classes/stats/',
    ENROLL: (id: string) => `/live-classes/${id}/enroll/`,
    UNENROLL: (id: string) => `/live-classes/${id}/unenroll/`,
    START: (id: string) => `/live-classes/${id}/start/`,
    END: (id: string) => `/live-classes/${id}/end/`,
    CANCEL: (id: string) => `/live-classes/${id}/cancel/`,
  },
  EXAMS: {
    BASE: '/exams/exams/',
    DETAIL: (id: string) => `/exams/exams/${id}/`,
    ACTIVE: '/exams/exams/active/',
    SUBMISSIONS: '/exams/submissions/',
    SUBMISSION_DETAIL: (id: string) => `/exams/submissions/${id}/`,
    MY_RESULTS: '/exams/submissions/my_results/',
  },
  STUDENTS: {
    BASE: '/students/students/',
    ME: '/students/students/me/',
    HONOUR_ROLL: '/students/students/honour_roll/',
    REGISTRY_SUMMARY: '/students/students/registry_summary/',
    BULK_UPLOAD: '/students/students/bulk_upload/',
    MY_CHILDREN: '/students/students/my_children/',
    PARENT_LINKS: '/students/parent-student-links/',
    CLASS_LIST: (cls: string) => `/students/students/class_list/?class_name=${encodeURIComponent(cls)}`,
    DETAIL: (id: string) => `/students/students/${id}/`,
    LINK_PARENT: (id: string) => `/students/students/${id}/link_parent/`,
    STUDENT_CARD: (id: string) => `/students/students/${id}/student_card/`,
    ADMISSION_FORM: (id: string) => `/students/students/${id}/admission_form/`,
  },
  ASSIGNMENTS: {
    BASE: '/assignments/assignments/',
    DETAIL: (id: string) => `/assignments/assignments/${id}/`,
    SUBMISSIONS: '/assignments/submissions/',
    SUBMISSION_DETAIL: (id: string) => `/assignments/submissions/${id}/`,
    MY_SUBMISSIONS: '/assignments/submissions/my_submissions/',
    GRADE_SUBMISSION: (id: string) => `/assignments/submissions/${id}/grade/`,
  },
  GRADES: {
    SUBJECTS: '/grades/subjects/',
    SUBJECT_DETAIL: (id: string) => `/grades/subjects/${id}/`,
    STUDENT_ENROLLMENTS: '/grades/student-enrollments/',
    STUDENT_ENROLLMENT_DETAIL: (id: string) => `/grades/student-enrollments/${id}/`,
    MATERIALS: '/grades/materials/',
    MATERIAL_DETAIL: (id: string) => `/grades/materials/${id}/`,
    SEQUENCES: '/grades/sequences/',
    SEQUENCE_DETAIL: (id: string) => `/grades/sequences/${id}/`,
    GRADES: '/grades/grades/',
    GRADE_DETAIL: (id: string) => `/grades/grades/${id}/`,
    BULK_CREATE: '/grades/grades/bulk_create/',
    REPORT_CARD: (studentId: string, sequenceId: string) =>
      `/grades/grades/report_card/?student_id=${studentId}&sequence_id=${sequenceId}`,
    CLASS_RESULTS: (cls: string, seqId: string) =>
      `/grades/grades/class_results/?class_name=${encodeURIComponent(cls)}&sequence_id=${seqId}`,
    TERM_RESULTS: '/grades/term-results/',
    ANNUAL_RESULTS: '/grades/annual-results/',
  },
  ATTENDANCE: {
    SESSIONS: '/attendance/sessions/',
    SESSION_DETAIL: (id: string) => `/attendance/sessions/${id}/`,
    RECORDS: '/attendance/records/',
    RECORD_DETAIL: (id: string) => `/attendance/records/${id}/`,
    BULK_RECORD: '/attendance/records/bulk_record/',
    MY_ATTENDANCE: '/attendance/records/my_attendance/',
    STUDENT_SUMMARY: (id: string) => `/attendance/records/student_summary/?student_id=${id}`,
    CLASS_REPORT: (cls: string) => `/attendance/records/class_report/?class_name=${encodeURIComponent(cls)}`,
    ABSENT_TODAY: '/attendance/records/absent_students_today/',
    TEACHER_ATTENDANCE: '/attendance/teacher-attendance/',
    TEACHER_ATTENDANCE_DETAIL: (id: string) => `/attendance/teacher-attendance/${id}/`,
  },
  FEES: {
    STRUCTURES: '/fees/fee-structures/',
    STRUCTURE_DETAIL: (id: string) => `/fees/fee-structures/${id}/`,
    PAYMENTS: '/fees/payments/',
    PAYMENT_DETAIL: (id: string) => `/fees/payments/${id}/`,
    MY_PAYMENTS: '/fees/payments/my_payments/',
    CONFIRM: (id: string) => `/fees/payments/${id}/confirm/`,
    REJECT: (id: string) => `/fees/payments/${id}/reject/`,
    REVENUE_REPORT: '/fees/payments/revenue_report/',
    OUTSTANDING: '/fees/payments/outstanding_fees/',
    RECEIPT: (id: string) => `/fees/payments/${id}/generate_receipt/`,
    INVOICES: '/fees/invoices/',
    INVOICE_DETAIL: (id: string) => `/fees/invoices/${id}/`,
    SCHOOL_FEE_ASSIGNMENTS: '/fees/school-fee-assignments/',
    SCHOOL_FEE_ASSIGNMENT_DETAIL: (id: string) => `/fees/school-fee-assignments/${id}/`,
    STUDENT_SCHOOL_FEES: '/fees/student-school-fees/',
    STUDENT_SCHOOL_FEE_DETAIL: (id: string) => `/fees/student-school-fees/${id}/`,
    SCHOOL_FEE_SUMMARY: '/fees/student-school-fees/summary/',
    SCHOOL_FEE_REPORT_PDF: '/fees/student-school-fees/export-pdf/',
  },
  LIBRARY: {
    CATEGORIES: '/library/categories/',
    CATEGORY_DETAIL: (id: string) => `/library/categories/${id}/`,
    BOOKS: '/library/books/',
    BOOK_DETAIL: (id: string) => `/library/books/${id}/`,
    SEARCH: '/library/books/search/',
    LOW_STOCK: '/library/books/low_stock/',
    LOANS: '/library/loans/',
    LOAN_DETAIL: (id: string) => `/library/loans/${id}/`,
    ISSUE: () => `/library/loans/issue/`,
    RETURN: (loanId: string) => `/library/loans/${loanId}/return_book/`,
    MY_LOANS: '/library/loans/my_loans/',
    OVERDUE: '/library/loans/overdue/',
    STATS: '/library/loans/stats/',
    REQUESTS: '/library/requests/',
    REQUEST_DETAIL: (id: string) => `/library/requests/${id}/`,
    REQUEST_APPROVE: (id: string) => `/library/requests/${id}/approve/`,
    REQUEST_REJECT: (id: string) => `/library/requests/${id}/reject/`,
    REQUEST_FULFILL: (id: string) => `/library/requests/${id}/fulfill/`,
  },
  ANNOUNCEMENTS: {
    BASE: '/announcements/announcements/',
    DETAIL: (id: string) => `/announcements/announcements/${id}/`,
    MY_FEED: '/announcements/announcements/my_announcements/',
    PINNED: '/announcements/announcements/pinned/',
    MARK_READ: (id: string) => `/announcements/announcements/${id}/mark_read/`,
    PLATFORM_WIDE: '/announcements/announcements/platform_wide/',
  },
  COMMUNITY: {
    TESTIMONIES: '/community/testimonies/',
    TESTIMONY_DETAIL: (id: string) => `/community/testimonies/${id}/`,
    PENDING_TESTIMONIES: '/community/testimonies/pending/',
    APPROVE_TESTIMONY: (id: string) => `/community/testimonies/${id}/approve/`,
    REJECT_TESTIMONY: (id: string) => `/community/testimonies/${id}/reject/`,
    BLOGS: '/community/blogs/',
    BLOG_DETAIL: (id: string) => `/community/blogs/${id}/`,
    PUBLISH_BLOG: (id: string) => `/community/blogs/${id}/publish/`,
    VIEW_BLOG: (id: string) => `/community/blogs/${id}/view/`,
    COMMENTS: '/community/comments/',
    COMMENT_DETAIL: (id: string) => `/community/comments/${id}/`,
  },
  FEEDBACK: {
    BASE: '/feedback/feedback/',
    DETAIL: (id: string) => `/feedback/feedback/${id}/`,
    MY_FEEDBACK: '/feedback/feedback/my_feedback/',
    RESOLVE: (id: string) => `/feedback/feedback/${id}/resolve/`,
    RESPOND: (id: string) => `/feedback/feedback/${id}/respond/`,
    STATS: '/feedback/feedback/stats/',
  },
  ORDERS: {
    BASE: '/orders/orders/',
    DETAIL: (id: string) => `/orders/orders/${id}/`,
    PROCESS: (id: string) => `/orders/orders/${id}/process/`,
    STATS: '/orders/orders/stats/',
  },
  SUPPORT: {
    BASE: '/support/contributions/',
    DETAIL: (id: string) => `/support/contributions/${id}/`,
    VERIFY: (id: string) => `/support/contributions/${id}/verify/`,
    REJECT: (id: string) => `/support/contributions/${id}/reject/`,
    STATS: '/support/contributions/stats/',
  },
  STAFF_REMARKS: {
    BASE: '/staff-remarks/remarks/',
    DETAIL: (id: string) => `/staff-remarks/remarks/${id}/`,
    MY_REMARKS: '/staff-remarks/remarks/my_remarks/',
    ACKNOWLEDGE: (id: string) => `/staff-remarks/remarks/${id}/acknowledge/`,
    REPORT: (staffId: string) => `/staff-remarks/remarks/download_report/?staff=${staffId}`,
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations/',
    CONVERSATION_DETAIL: (id: string) => `/chat/conversations/${id}/`,
    MESSAGES_BASE: '/chat/messages/',
    MESSAGES: (convId: string) => `/chat/conversations/${convId}/messages/`,
    MESSAGE_DETAIL: (msgId: string) => `/chat/messages/${msgId}/`,
    DIRECT: '/chat/conversations/get-or-create-direct/',
    RELATED_USERS: '/chat/conversations/related-users/',
    TEACHER_GROUP_OPTIONS: '/chat/conversations/teacher-group-options/',
    CREATE_TEACHER_GROUP: '/chat/conversations/create-teacher-group/',
    SETTINGS: (convId: string) => `/chat/conversations/${convId}/settings/`,
    REMOVE_PARTICIPANT: (convId: string) => `/chat/conversations/${convId}/remove-participant/`,
    ADD_PARTICIPANT: (convId: string) => `/chat/conversations/${convId}/add-participant/`,
    MARK_READ: (convId: string) => `/chat/conversations/${convId}/mark-read/`,
    DELETE_MESSAGE: (msgId: string) => `/chat/messages/${msgId}/`,
  },
  AI: {
    REQUESTS: '/ai/requests/',
    REQUEST_DETAIL: (id: string) => `/ai/requests/${id}/`,
    STUDY_PLAN: '/ai/requests/generate-study-plan/',
    ANALYZE_GRADES: '/ai/requests/analyze-grades/',
    ATTENDANCE_INSIGHT: '/ai/requests/attendance-insight/',
    EXAM_PREP: '/ai/requests/exam-prep/',
    PARENT_REPORT: '/ai/requests/parent-report/',
    PLATFORM_INSIGHTS: '/ai/requests/platform-insights/',
    INSIGHTS: '/ai/insights/',
    INSIGHT_DETAIL: (id: string) => `/ai/insights/${id}/`,
    GENERATE_INSIGHTS: '/ai/insights/generate-insights/',
    DIRECT_CHAT: '/ai/chat/',
  },
} as const;
